# =============================================================================
# GHERKIN SYNTAX GUIDE — read this before the scenarios below
# =============================================================================
#
# Feature       — the area of the app being tested (one per file)
# Background    — steps that run before EVERY scenario in this file (like beforeEach)
# Scenario      — one specific test case with a fixed set of steps
# Scenario Outline + Examples — a template scenario that runs once per row
#                               in the Examples table (data-driven testing)
#
# Keywords inside a scenario:
#   Given  — the starting state / precondition
#   When   — the action the user takes
#   Then   — the expected outcome
#   And    — continues the previous keyword (Given/When/Then), just for readability
#   But    — same as And, used to express a negative continuation
#
# Tags (@ prefix) — used to filter which tests to run in CI
#   @smoke        — run on every deploy, must pass
#   @regression   — full suite, run before release
#   @compliance   — regulatory requirements, always run
#   @known-bug    — scenario documents expected behaviour but is currently blocked
#                   by a known defect; skip in CI until bug is fixed
# =============================================================================

Feature: Trading Account Registration — Happy Path
  As a new user
  I want to register a trading account
  So that I can access the trading platform

  # Background runs before every Scenario in this file.
  # Think of it as a beforeEach that sets the starting URL.
  Background:
    Given I am on the registration page

  # ---------------------------------------------------------------------------
  # SCENARIO — the full happy path.
  # Tagged @known-bug because BUG-030 (T&C checkbox) currently blocks submission.
  # Data is generated by faker in the test — Gherkin describes what kind of
  # data is used, not the actual values. Country stays hardcoded because it is
  # a deliberate business choice (Japan = non-restricted, non-EU).
  # ---------------------------------------------------------------------------
  @smoke @regression @known-bug
  Scenario: Successful registration with valid data from a non-restricted country
    Given I am on the "Individual" tab
    When I fill in "First name" with a valid first name
    And I fill in "Last name" with a valid last name
    And I fill in "Email" with a unique valid email
    And I fill in "Password" with a valid password
    And I select "Japan" as the country of residence
    And I accept the Terms and Conditions
    And I click the submit button
    Then I should be redirected to the account dashboard

